FROM golang:bookworm

WORKDIR /app
COPY project ./project
WORKDIR /app/project

RUN go build .

RUN printf '#!/bin/sh\nwhile true; do\n sleep 1\n  ./project -server "$ELEVATOR_SERVER"\n  echo "Controller crashed, restarting..."\ndone\n' > run.sh && chmod +x run.sh

CMD ./run.sh
